stages:
  - build
  - deploy

make:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make

deploy:
  stage: deploy
  script:
    - pwd
    - cd build
    - cd bin
    - ./adventure2016